#!/usr/bin/env python3
"""Fasting cycle rework: add/replace the window + lead-reminder strings in every
Android locale pack. One-shot; deleted at the shipping release together with the
other insert_fasting_* scripts.

- Adds new keys (window labels, lead rows, soon-texts).
- REPLACES notif_fasting_goal_text (drops %1$d), settings_fasting_goal_summary
  ("%1$d h fast") and settings_fasting_goal_wheel_help (two-window copy) so the
  placeholder check (ph_set must equal EN) and copy check stay green.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
RES = ROOT / "android/app/src/main/res"

# locale-dir -> {name: (value, replace_existing)}
STRINGS = {
    "values-ar": {
        "fasting_fast_starts_in": ("يبدأ الصيام خلال %1$s", False),
        "fasting_eating_progress": ("%1$s من %2$d ساعات أكل", False),
        "settings_fasting_eat_window": ("نافذة الأكل", False),
        "settings_fasting_goal_summary": ("%1$d ساعة صيام", True),
        "settings_fasting_goal_summary_both": ("%1$d ساعة صيام · %2$d ساعة أكل", False),
        "settings_fasting_goal_wheel_help": ("اختر بروتوكولًا شائعًا أو اضبط نوافذ الصيام والأكل بنفسك. 0 = بلا هدف.", True),
        "settings_fasting_end_reminder": ("تذكير إنهاء الصيام", False),
        "settings_fasting_reminder_lead_end": ("قبل انتهاء الصيام", False),
        "settings_fasting_reminder_lead_start": ("قبل بدء الصيام", False),
        "settings_fasting_reminder_lead_unit": ("دقيقة", False),
        "settings_fasting_reminder_lead_summary": ("قبل %1$d دقيقة", False),
        "settings_fasting_reminder_lead_now": ("عند الحد", False),
        "settings_fasting_reminder_help": ("المدد قبل كل دورة: تذكير البدء قبل إغلاق نافذة الأكل، وتذكير الإفطار قبل بلوغ الهدف. 0 = عند الحد تمامًا.", False),
        "notif_fasting_goal_text": ("اكتمل صيامك — يمكنك الأكل الآن.", True),
        "notif_fasting_end_soon_title": ("ينتهي الصيام قريبًا", False),
        "notif_fasting_end_soon_text": ("ينتهي صيامك خلال %1$d دقيقة — ستفتح نافذة الأكل حينها.", False),
        "notif_fasting_start_soon_title": ("يبدأ الصيام قريبًا", False),
        "notif_fasting_start_soon_text": ("تُغلق نافذة الأكل خلال %1$d دقيقة — ابدأ صيامك حينها.", False),
    },
    "values-az": {
        "fasting_fast_starts_in": ("Oruc %1$s sonra başlayır", False),
        "fasting_eating_progress": ("%2$d saat yeməkdən %1$s", False),
        "settings_fasting_eat_window": ("Yemək pəncərəsi", False),
        "settings_fasting_goal_summary": ("%1$d saat oruc", True),
        "settings_fasting_goal_summary_both": ("%1$d saat oruc · %2$d saat yemək", False),
        "settings_fasting_goal_wheel_help": ("Məşhur protokoldan seçin və ya öz oruc və yemək pəncərələrinizi təyin edin. 0 = hədəf yoxdur.", True),
        "settings_fasting_end_reminder": ("Orucu bitirmə xatırlatması", False),
        "settings_fasting_reminder_lead_end": ("Oruc bitməzdən əvvəl", False),
        "settings_fasting_reminder_lead_start": ("Oruc başlamazdan əvvəl", False),
        "settings_fasting_reminder_lead_unit": ("dəq", False),
        "settings_fasting_reminder_lead_summary": ("%1$d dəq əvvəl", False),
        "settings_fasting_reminder_lead_now": ("Sərhəddə", False),
        "settings_fasting_reminder_help": ("Vaxtlar hər dövrə üçündür: başlama xatırlatması yemək pəncərəsi bağlanmazdan əvvəl, bitirmə xatırlatması hədəfə çatmazdan əvvəl. 0 = tam sərhəddə.", False),
        "notif_fasting_goal_text": ("Orucunuz tamamlandı — indi yeyə bilərsiniz.", True),
        "notif_fasting_end_soon_title": ("Oruc tezliklə bitir", False),
        "notif_fasting_end_soon_text": ("Orucunuz %1$d dəq sonra bitir — yemək pəncərəsi o zaman açılır.", False),
        "notif_fasting_start_soon_title": ("Oruc tezliklə başlayır", False),
        "notif_fasting_start_soon_text": ("Yemək pəncərəsi %1$d dəq sonra bağlanır — o zaman oruca başlayın.", False),
    },
    "values-de": {
        "fasting_fast_starts_in": ("Fasten startet in %1$s", False),
        "fasting_eating_progress": ("%1$s von %2$d h Essen", False),
        "settings_fasting_eat_window": ("Essensfenster", False),
        "settings_fasting_goal_summary": ("%1$d h fasten", True),
        "settings_fasting_goal_summary_both": ("%1$d h fasten · %2$d h essen", False),
        "settings_fasting_goal_wheel_help": ("Wähle einen gängigen Protokoll oder stell dein eigenes Fasten- und Essensfenster ein. 0 = kein Ziel.", True),
        "settings_fasting_end_reminder": ("Fastenende-Erinnerung", False),
        "settings_fasting_reminder_lead_end": ("Vor dem Fastenende", False),
        "settings_fasting_reminder_lead_start": ("Vor dem Fastenbeginn", False),
        "settings_fasting_reminder_lead_unit": ("Min", False),
        "settings_fasting_reminder_lead_summary": ("%1$d Min vorher", False),
        "settings_fasting_reminder_lead_now": ("Genau an der Grenze", False),
        "settings_fasting_reminder_help": ("Vorlaufzeiten pro Zyklus: Die Start-Erinnerung erscheint vor dem Schließen des Essensfensters, die Fastenende-Erinnerung vor dem Erreichen des Ziels. 0 = genau an der Grenze.", False),
        "notif_fasting_goal_text": ("Dein Fasten ist abgeschlossen — du kannst jetzt essen.", True),
        "notif_fasting_end_soon_title": ("Fasten endet bald", False),
        "notif_fasting_end_soon_text": ("Dein Fasten endet in %1$d Min — dann öffnet sich dein Essensfenster.", False),
        "notif_fasting_start_soon_title": ("Fasten startet bald", False),
        "notif_fasting_start_soon_text": ("Dein Essensfenster schließt in %1$d Min — starte dann dein Fasten.", False),
    },
    "values-es": {
        "fasting_fast_starts_in": ("El ayuno empieza en %1$s", False),
        "fasting_eating_progress": ("%1$s de %2$d h de comida", False),
        "settings_fasting_eat_window": ("Ventana de comida", False),
        "settings_fasting_goal_summary": ("%1$d h de ayuno", True),
        "settings_fasting_goal_summary_both": ("%1$d h de ayuno · %2$d h de comida", False),
        "settings_fasting_goal_wheel_help": ("Elige un protocolo popular o configura tus propias ventanas de ayuno y comida. 0 = sin objetivo.", True),
        "settings_fasting_end_reminder": ("Recordatorio de fin de ayuno", False),
        "settings_fasting_reminder_lead_end": ("Antes de que termine el ayuno", False),
        "settings_fasting_reminder_lead_start": ("Antes de que empiece el ayuno", False),
        "settings_fasting_reminder_lead_unit": ("min", False),
        "settings_fasting_reminder_lead_summary": ("%1$d min antes", False),
        "settings_fasting_reminder_lead_now": ("En el límite", False),
        "settings_fasting_reminder_help": ("Los tiempos de aviso son por ciclo: el de inicio suena antes de cerrar la ventana de comida y el de fin antes de alcanzar el objetivo. 0 = justo en el límite.", False),
        "notif_fasting_goal_text": ("Tu ayuno ha terminado: ya puedes comer.", True),
        "notif_fasting_end_soon_title": ("El ayuno termina pronto", False),
        "notif_fasting_end_soon_text": ("Tu ayuno termina en %1$d min: entonces se abre tu ventana de comida.", False),
        "notif_fasting_start_soon_title": ("El ayuno empieza pronto", False),
        "notif_fasting_start_soon_text": ("Tu ventana de comida se cierra en %1$d min: empieza tu ayuno entonces.", False),
    },
    "values-fr": {
        "fasting_fast_starts_in": ("Le jeûne commence dans %1$s", False),
        "fasting_eating_progress": ("%1$s sur %2$d h de repas", False),
        "settings_fasting_eat_window": ("Fenêtre de repas", False),
        "settings_fasting_goal_summary": ("%1$d h de jeûne", True),
        "settings_fasting_goal_summary_both": ("%1$d h de jeûne · %2$d h de repas", False),
        "settings_fasting_goal_wheel_help": ("Choisissez un protocole populaire ou réglez vos propres fenêtres de jeûne et de repas. 0 = aucun objectif.", True),
        "settings_fasting_end_reminder": ("Rappel de fin de jeûne", False),
        "settings_fasting_reminder_lead_end": ("Avant la fin du jeûne", False),
        "settings_fasting_reminder_lead_start": ("Avant le début du jeûne", False),
        "settings_fasting_reminder_lead_unit": ("min", False),
        "settings_fasting_reminder_lead_summary": ("%1$d min avant", False),
        "settings_fasting_reminder_lead_now": ("À la limite", False),
        "settings_fasting_reminder_help": ("Les délais sont par cycle : le rappel de début sonne avant la fermeture de la fenêtre de repas, celui de fin avant l\'atteinte de l\'objectif. 0 = exactement à la limite.", False),
        "notif_fasting_goal_text": ("Votre jeûne est terminé : vous pouvez manger maintenant.", True),
        "notif_fasting_end_soon_title": ("Jeûne bientôt terminé", False),
        "notif_fasting_end_soon_text": ("Votre jeûne se termine dans %1$d min — votre fenêtre de repas s\'ouvre alors.", False),
        "notif_fasting_start_soon_title": ("Jeûne bientôt commencé", False),
        "notif_fasting_start_soon_text": ("Votre fenêtre de repas se ferme dans %1$d min — démarrez votre jeûne alors.", False),
    },
    "values-hi": {
        "fasting_fast_starts_in": ("उपवास %1$s में शुरू होगा", False),
        "fasting_eating_progress": ("खाने के %2$d घंटों में से %1$s", False),
        "settings_fasting_eat_window": ("खाने की विंडो", False),
        "settings_fasting_goal_summary": ("%1$d घंटे उपवास", True),
        "settings_fasting_goal_summary_both": ("%1$d घंटे उपवास · %2$d घंटे खाना", False),
        "settings_fasting_goal_wheel_help": ("कोई लोकप्रिय तरीका चुनें या अपनी उपवास और खाने की विंडो खुद सेट करें। 0 = कोई लक्ष्य नहीं।", True),
        "settings_fasting_end_reminder": ("उपवास समाप्ति अनुस्मारक", False),
        "settings_fasting_reminder_lead_end": ("उपवास समाप्त होने से पहले", False),
        "settings_fasting_reminder_lead_start": ("उपवास शुरू होने से पहले", False),
        "settings_fasting_reminder_lead_unit": ("मिनट", False),
        "settings_fasting_reminder_lead_summary": ("%1$d मिनट पहले", False),
        "settings_fasting_reminder_lead_now": ("सीमा पर", False),
        "settings_fasting_reminder_help": ("समय हर चक्र के लिए है: शुरुआत अनुस्मारक खाने की विंडो बंद होने से पहले, समाप्ति अनुस्मारक लक्ष्य पूरा होने से पहले। 0 = बिल्कुल सीमा पर।", False),
        "notif_fasting_goal_text": ("आपका उपवास पूरा हुआ — अब आप खा सकते हैं।", True),
        "notif_fasting_end_soon_title": ("उपवास जल्द समाप्त होगा", False),
        "notif_fasting_end_soon_text": ("आपका उपवास %1$d मिनट में समाप्त होगा — तब खाने की विंडो खुलेगी।", False),
        "notif_fasting_start_soon_title": ("उपवास जल्द शुरू होगा", False),
        "notif_fasting_start_soon_text": ("आपकी खाने की विंडो %1$d मिनट में बंद होगी — तब उपवास शुरू करें।", False),
    },
    "values-it": {
        "fasting_fast_starts_in": ("Il digiuno inizia tra %1$s", False),
        "fasting_eating_progress": ("%1$s di %2$d h di pasti", False),
        "settings_fasting_eat_window": ("Finestra dei pasti", False),
        "settings_fasting_goal_summary": ("%1$d h di digiuno", True),
        "settings_fasting_goal_summary_both": ("%1$d h di digiuno · %2$d h di pasti", False),
        "settings_fasting_goal_wheel_help": ("Scegli un protocollo popolare o imposta le tue finestre di digiuno e pasti. 0 = nessun obiettivo.", True),
        "settings_fasting_end_reminder": ("Promemoria fine digiuno", False),
        "settings_fasting_reminder_lead_end": ("Prima della fine del digiuno", False),
        "settings_fasting_reminder_lead_start": ("Prima dell\'inizio del digiuno", False),
        "settings_fasting_reminder_lead_unit": ("min", False),
        "settings_fasting_reminder_lead_summary": ("%1$d min prima", False),
        "settings_fasting_reminder_lead_now": ("Al limite", False),
        "settings_fasting_reminder_help": ("Gli anticipi sono per ciclo: il promemoria di inizio suona prima della chiusura della finestra dei pasti, quello di fine prima dell\'obiettivo. 0 = esattamente al limite.", False),
        "notif_fasting_goal_text": ("Il tuo digiuno è completo: ora puoi mangiare.", True),
        "notif_fasting_end_soon_title": ("Il digiuno finisce presto", False),
        "notif_fasting_end_soon_text": ("Il tuo digiuno finisce tra %1$d min: la tua finestra dei pasti si apre allora.", False),
        "notif_fasting_start_soon_title": ("Il digiuno inizia presto", False),
        "notif_fasting_start_soon_text": ("La tua finestra dei pasti si chiude tra %1$d min: inizia il digiuno allora.", False),
    },
    "values-ja": {
        "fasting_fast_starts_in": ("ファスティングまで %1$s", False),
        "fasting_eating_progress": ("食事 %2$d 時間のうち %1$s", False),
        "settings_fasting_eat_window": ("食事時間", False),
        "settings_fasting_goal_summary": ("%1$d 時間ファスティング", True),
        "settings_fasting_goal_summary_both": ("%1$d 時間ファスティング · %2$d 時間食事", False),
        "settings_fasting_goal_wheel_help": ("一般的なプロトコルを選ぶか、自分でファスティングと食事の時間を設定できます。0 = 目標なし。", True),
        "settings_fasting_end_reminder": ("終了リマインダー", False),
        "settings_fasting_reminder_lead_end": ("ファスティング終了前", False),
        "settings_fasting_reminder_lead_start": ("ファスティング開始前", False),
        "settings_fasting_reminder_lead_unit": ("分", False),
        "settings_fasting_reminder_lead_summary": ("%1$d 分前", False),
        "settings_fasting_reminder_lead_now": ("ちょうど境界で", False),
        "settings_fasting_reminder_help": ("リード時間はサイクルごとです。開始通知は食事時間の終了前に、終了通知は目標達成の前に送られます。0 = ちょうど境界で。", False),
        "notif_fasting_goal_text": ("ファスティングが完了しました。もう食べられます。", True),
        "notif_fasting_end_soon_title": ("ファスティングまもなく終了", False),
        "notif_fasting_end_soon_text": ("%1$d 分後にファスティングが終了します。食事時間が始まります。", False),
        "notif_fasting_start_soon_title": ("ファスティングまもなく開始", False),
        "notif_fasting_start_soon_text": ("%1$d 分後に食事時間が終了します。ファスティングを始めましょう。", False),
    },
    "values-ko": {
        "fasting_fast_starts_in": ("단식 시작까지 %1$s", False),
        "fasting_eating_progress": ("식사 %2$d시간 중 %1$s", False),
        "settings_fasting_eat_window": ("식사 시간", False),
        "settings_fasting_goal_summary": ("단식 %1$d시간", True),
        "settings_fasting_goal_summary_both": ("단식 %1$d시간 · 식사 %2$d시간", False),
        "settings_fasting_goal_wheel_help": ("인기 프로토콜을 선택하거나 나만의 단식·식사 시간을 설정하세요. 0 = 목표 없음.", True),
        "settings_fasting_end_reminder": ("단식 종료 알림", False),
        "settings_fasting_reminder_lead_end": ("단식 종료 전", False),
        "settings_fasting_reminder_lead_start": ("단식 시작 전", False),
        "settings_fasting_reminder_lead_unit": ("분", False),
        "settings_fasting_reminder_lead_summary": ("%1$d분 전", False),
        "settings_fasting_reminder_lead_now": ("경계 시점", False),
        "settings_fasting_reminder_help": ("리드 시간은 주기별입니다. 시작 알림은 식사 시간이 끝나기 전, 종료 알림은 목표 도달 전에 울립니다. 0 = 경계에서 정확히.", False),
        "notif_fasting_goal_text": ("단식이 완료되었습니다. 이제 식사를 시작할 수 있습니다.", True),
        "notif_fasting_end_soon_title": ("단식 곧 종료", False),
        "notif_fasting_end_soon_text": ("%1$d분 후 단식이 종료됩니다. 식사 시간이 열립니다.", False),
        "notif_fasting_start_soon_title": ("단식 곧 시작", False),
        "notif_fasting_start_soon_text": ("%1$d분 후 식사 시간이 종료됩니다. 단식을 시작하세요.", False),
    },
    "values-nl": {
        "fasting_fast_starts_in": ("Vasten start over %1$s", False),
        "fasting_eating_progress": ("%1$s van %2$d u eten", False),
        "settings_fasting_eat_window": ("Eetvenster", False),
        "settings_fasting_goal_summary": ("%1$d u vasten", True),
        "settings_fasting_goal_summary_both": ("%1$d u vasten · %2$d u eten", False),
        "settings_fasting_goal_wheel_help": ("Kies een populair protocol of stel je eigen vasten- en eetvenster in. 0 = geen doel.", True),
        "settings_fasting_end_reminder": ("Einde-vasten-herinnering", False),
        "settings_fasting_reminder_lead_end": ("Voor het einde van het vasten", False),
        "settings_fasting_reminder_lead_start": ("Voor het begin van het vasten", False),
        "settings_fasting_reminder_lead_unit": ("min", False),
        "settings_fasting_reminder_lead_summary": ("%1$d min van tevoren", False),
        "settings_fasting_reminder_lead_now": ("Precies op de grens", False),
        "settings_fasting_reminder_help": ("Voorlooptijden gelden per cyclus: de startherinnering klinkt voordat je eetvenster sluit, de einde-herinnering voordat je doel wordt bereikt. 0 = precies op de grens.", False),
        "notif_fasting_goal_text": ("Je vasten is voltooid — je kunt nu eten.", True),
        "notif_fasting_end_soon_title": ("Vasten eindigt binnenkort", False),
        "notif_fasting_end_soon_text": ("Je vasten eindigt over %1$d min — je eetvenster gaat dan open.", False),
        "notif_fasting_start_soon_title": ("Vasten begint binnenkort", False),
        "notif_fasting_start_soon_text": ("Je eetvenster sluit over %1$d min — start dan je vasten.", False),
    },
    "values-pl": {
        "fasting_fast_starts_in": ("Post zaczyna się za %1$s", False),
        "fasting_eating_progress": ("%1$s z %2$d h jedzenia", False),
        "settings_fasting_eat_window": ("Okno jedzenia", False),
        "settings_fasting_goal_summary": ("%1$d h postu", True),
        "settings_fasting_goal_summary_both": ("%1$d h postu · %2$d h jedzenia", False),
        "settings_fasting_goal_wheel_help": ("Wybierz popularny protokół lub ustaw własne okna postu i jedzenia. 0 = brak celu.", True),
        "settings_fasting_end_reminder": ("Przypomnienie o zakończeniu postu", False),
        "settings_fasting_reminder_lead_end": ("Przed końcem postu", False),
        "settings_fasting_reminder_lead_start": ("Przed rozpoczęciem postu", False),
        "settings_fasting_reminder_lead_unit": ("min", False),
        "settings_fasting_reminder_lead_summary": ("%1$d min wcześniej", False),
        "settings_fasting_reminder_lead_now": ("Dokładnie na granicy", False),
        "settings_fasting_reminder_help": ("Czasy wyprzedzenia są per cykl: przypomnienie o rozpoczęciu pojawia się przed zamknięciem okna jedzenia, o zakończeniu — przed osiągnięciem celu. 0 = dokładnie na granicy.", False),
        "notif_fasting_goal_text": ("Twój post zakończony — możesz teraz jeść.", True),
        "notif_fasting_end_soon_title": ("Post wkrótce się kończy", False),
        "notif_fasting_end_soon_text": ("Twój post kończy się za %1$d min — wtedy otwiera się okno jedzenia.", False),
        "notif_fasting_start_soon_title": ("Post wkrótce się zacznie", False),
        "notif_fasting_start_soon_text": ("Twoje okno jedzenia zamyka się za %1$d min — rozpocznij wtedy post.", False),
    },
    "values-pt-rBR": {
        "fasting_fast_starts_in": ("O jejum começa em %1$s", False),
        "fasting_eating_progress": ("%1$s de %2$d h de refeições", False),
        "settings_fasting_eat_window": ("Janela de refeições", False),
        "settings_fasting_goal_summary": ("%1$d h de jejum", True),
        "settings_fasting_goal_summary_both": ("%1$d h de jejum · %2$d h de refeições", False),
        "settings_fasting_goal_wheel_help": ("Escolha um protocolo popular ou defina suas próprias janelas de jejum e refeições. 0 = sem meta.", True),
        "settings_fasting_end_reminder": ("Lembrete de fim de jejum", False),
        "settings_fasting_reminder_lead_end": ("Antes do fim do jejum", False),
        "settings_fasting_reminder_lead_start": ("Antes do início do jejum", False),
        "settings_fasting_reminder_lead_unit": ("min", False),
        "settings_fasting_reminder_lead_summary": ("%1$d min antes", False),
        "settings_fasting_reminder_lead_now": ("No limite", False),
        "settings_fasting_reminder_help": ("Os avisos são por ciclo: o de início toca antes do fechamento da janela de refeições e o de fim antes de atingir a meta. 0 = exatamente no limite.", False),
        "notif_fasting_goal_text": ("Seu jejum terminou: você já pode comer.", True),
        "notif_fasting_end_soon_title": ("O jejum termina em breve", False),
        "notif_fasting_end_soon_text": ("Seu jejum termina em %1$d min — sua janela de refeições abre então.", False),
        "notif_fasting_start_soon_title": ("O jejum começa em breve", False),
        "notif_fasting_start_soon_text": ("Sua janela de refeições fecha em %1$d min — comece seu jejum então.", False),
    },
    "values-ro": {
        "fasting_fast_starts_in": ("Postul începe în %1$s", False),
        "fasting_eating_progress": ("%1$s din %2$d h de mese", False),
        "settings_fasting_eat_window": ("Fereastra de mese", False),
        "settings_fasting_goal_summary": ("%1$d h de post", True),
        "settings_fasting_goal_summary_both": ("%1$d h de post · %2$d h de mese", False),
        "settings_fasting_goal_wheel_help": ("Alege un protocol popular sau setează propriile ferestre de post și de mese. 0 = fără țintă.", True),
        "settings_fasting_end_reminder": ("Memento de sfârșit de post", False),
        "settings_fasting_reminder_lead_end": ("Înainte de sfârșitul postului", False),
        "settings_fasting_reminder_lead_start": ("Înainte de începerea postului", False),
        "settings_fasting_reminder_lead_unit": ("min", False),
        "settings_fasting_reminder_lead_summary": ("%1$d min înainte", False),
        "settings_fasting_reminder_lead_now": ("Exact la limită", False),
        "settings_fasting_reminder_help": ("Anticipările sunt per ciclu: mementoul de început sună înainte de închiderea ferestrei de mese, cel de sfârșit înainte de atingerea țintei. 0 = exact la limită.", False),
        "notif_fasting_goal_text": ("Postul tău s-a încheiat — poți mânca acum.", True),
        "notif_fasting_end_soon_title": ("Postul se termină în curând", False),
        "notif_fasting_end_soon_text": ("Postul tău se termină în %1$d min — fereastra de mese se deschide atunci.", False),
        "notif_fasting_start_soon_title": ("Postul începe în curând", False),
        "notif_fasting_start_soon_text": ("Fereastra ta de mese se închide în %1$d min — începe postul atunci.", False),
    },
    "values-ru": {
        "fasting_fast_starts_in": ("Пост начнётся через %1$s", False),
        "fasting_eating_progress": ("%1$s из %2$d ч приёма пищи", False),
        "settings_fasting_eat_window": ("Окно приёма пищи", False),
        "settings_fasting_goal_summary": ("%1$d ч поста", True),
        "settings_fasting_goal_summary_both": ("%1$d ч поста · %2$d ч приёма пищи", False),
        "settings_fasting_goal_wheel_help": ("Выберите популярный протокол или задайте свои окна поста и приёма пищи. 0 = без цели.", True),
        "settings_fasting_end_reminder": ("Напоминание о конце поста", False),
        "settings_fasting_reminder_lead_end": ("Перед концом поста", False),
        "settings_fasting_reminder_lead_start": ("Перед началом поста", False),
        "settings_fasting_reminder_lead_unit": ("мин", False),
        "settings_fasting_reminder_lead_summary": ("за %1$d мин", False),
        "settings_fasting_reminder_lead_now": ("Ровно на границе", False),
        "settings_fasting_reminder_help": ("Заблаговременность — по циклу: напоминание о начале срабатывает перед закрытием окна приёма пищи, о конце — перед достижением цели. 0 = ровно на границе.", False),
        "notif_fasting_goal_text": ("Ваш пост завершён — теперь можно есть.", True),
        "notif_fasting_end_soon_title": ("Пост скоро закончится", False),
        "notif_fasting_end_soon_text": ("Ваш пост закончится через %1$d мин — тогда откроется окно приёма пищи.", False),
        "notif_fasting_start_soon_title": ("Пост скоро начнётся", False),
        "notif_fasting_start_soon_text": ("Ваше окно приёма пищи закроется через %1$d мин — начните пост тогда.", False),
    },
    "values-tr": {
        "fasting_fast_starts_in": ("Oruç %1$s sonra başlar", False),
        "fasting_eating_progress": ("%2$d saat yemek penceresinin %1$s", False),
        "settings_fasting_eat_window": ("Yemek penceresi", False),
        "settings_fasting_goal_summary": ("%1$d saat oruç", True),
        "settings_fasting_goal_summary_both": ("%1$d saat oruç · %2$d saat yemek", False),
        "settings_fasting_goal_wheel_help": ("Popüler bir protokol seçin veya kendi oruç ve yemek pencerelerinizi ayarlayın. 0 = hedef yok.", True),
        "settings_fasting_end_reminder": ("Oruç bitiş hatırlatıcısı", False),
        "settings_fasting_reminder_lead_end": ("Oruç bitmeden önce", False),
        "settings_fasting_reminder_lead_start": ("Oruç başlamadan önce", False),
        "settings_fasting_reminder_lead_unit": ("dk", False),
        "settings_fasting_reminder_lead_summary": ("%1$d dk önce", False),
        "settings_fasting_reminder_lead_now": ("Tam sınırda", False),
        "settings_fasting_reminder_help": ("Ön süreler döngü başınadır: başlangıç hatırlatıcısı yemek penceresi kapanmadan önce, bitiş hatırlatıcısı hedefe ulaşmadan önce çalar. 0 = tam sınırda.", False),
        "notif_fasting_goal_text": ("Orucunuz tamamlandı — artık yemek yiyebilirsiniz.", True),
        "notif_fasting_end_soon_title": ("Oruç yakında bitiyor", False),
        "notif_fasting_end_soon_text": ("Orucunuz %1$d dk sonra bitiyor — yemek pencereniz o zaman açılır.", False),
        "notif_fasting_start_soon_title": ("Oruç yakında başlıyor", False),
        "notif_fasting_start_soon_text": ("Yemek pencereniz %1$d dk sonra kapanıyor — o zaman orucunuza başlayın.", False),
    },
    "values-uk": {
        "fasting_fast_starts_in": ("Пост почнеться через %1$s", False),
        "fasting_eating_progress": ("%1$s із %2$d год прийому їжі", False),
        "settings_fasting_eat_window": ("Вікно прийому їжі", False),
        "settings_fasting_goal_summary": ("%1$d год посту", True),
        "settings_fasting_goal_summary_both": ("%1$d год посту · %2$d год прийому їжі", False),
        "settings_fasting_goal_wheel_help": ("Виберіть популярний протокол або налаштуйте власні вікна посту й прийому їжі. 0 = без цілі.", True),
        "settings_fasting_end_reminder": ("Нагадування про кінець посту", False),
        "settings_fasting_reminder_lead_end": ("Перед кінцем посту", False),
        "settings_fasting_reminder_lead_start": ("Перед початком посту", False),
        "settings_fasting_reminder_lead_unit": ("хв", False),
        "settings_fasting_reminder_lead_summary": ("за %1$d хв", False),
        "settings_fasting_reminder_lead_now": ("Рівно на межі", False),
        "settings_fasting_reminder_help": ("Завчасність — за циклом: нагадування про початок спрацьовує перед закриттям вікна прийому їжі, про кінець — перед досягненням цілі. 0 = рівно на межі.", False),
        "notif_fasting_goal_text": ("Ваш пост завершено — тепер можна їсти.", True),
        "notif_fasting_end_soon_title": ("Пост незабаром завершиться", False),
        "notif_fasting_end_soon_text": ("Ваш пост завершиться через %1$d хв — тоді відкриється вікно прийому їжі.", False),
        "notif_fasting_start_soon_title": ("Пост незабаром почнеться", False),
        "notif_fasting_start_soon_text": ("Ваше вікно прийому їжі закриється через %1$d хв — почніть пост тоді.", False),
    },
    "values-zh-rCN": {
        "fasting_fast_starts_in": ("禁食将在 %1$s 后开始", False),
        "fasting_eating_progress": ("进食 %2$d 小时中的 %1$s", False),
        "settings_fasting_eat_window": ("进食窗口", False),
        "settings_fasting_goal_summary": ("禁食 %1$d 小时", True),
        "settings_fasting_goal_summary_both": ("禁食 %1$d 小时 · 进食 %2$d 小时", False),
        "settings_fasting_goal_wheel_help": ("选择常见方案或自行设置禁食和进食时间。0 = 无目标。", True),
        "settings_fasting_end_reminder": ("结束禁食提醒", False),
        "settings_fasting_reminder_lead_end": ("禁食结束前", False),
        "settings_fasting_reminder_lead_start": ("禁食开始前", False),
        "settings_fasting_reminder_lead_unit": ("分钟", False),
        "settings_fasting_reminder_lead_summary": ("提前 %1$d 分钟", False),
        "settings_fasting_reminder_lead_now": ("正好在边界", False),
        "settings_fasting_reminder_help": ("提前量按周期计算：开始提醒在进食窗口关闭前响起，结束提醒在达到目标前响起。0 = 正好在边界。", False),
        "notif_fasting_goal_text": ("您的禁食已完成，现在可以进食了。", True),
        "notif_fasting_end_soon_title": ("禁食即将结束", False),
        "notif_fasting_end_soon_text": ("您的禁食将在 %1$d 分钟后结束，届时进食窗口开启。", False),
        "notif_fasting_start_soon_title": ("禁食即将开始", False),
        "notif_fasting_start_soon_text": ("您的进食窗口将在 %1$d 分钟后关闭，届时请开始禁食。", False),
    },
}


def xml_escape(value: str) -> str:
    return value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def main() -> int:
    for folder, keys in STRINGS.items():
        path = RES / folder / "strings.xml"
        text = path.read_text(encoding="utf-8")
        for name, (value, replace_existing) in keys.items():
            entry = f'    <string name="{name}">{xml_escape(value)}</string>'
            if f'name="{name}"' in text:
                if not replace_existing:
                    print(f"skip {folder}/{name}: already present")
                    continue
                text = re.sub(
                    rf'^    <string name="{name}">.*</string>$',
                    entry,
                    text,
                    count=1,
                    flags=re.MULTILINE,
                )
            else:
                if "</resources>" not in text:
                    print(f"ERROR {folder}: no </resources> anchor")
                    return 1
                text = text.replace("</resources>", entry + "\n</resources>", 1)
        path.write_text(text, encoding="utf-8")
        print(f"ok {folder}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
