#!/usr/bin/env python3
"""Insert the fasting strings into every Android locale pack (before </resources>).

One-shot script for docs/local/PLAN_FASTING_TRACKER.md Phase 7 (deleted at the
release that ships the work). Anchor is the closing </resources> tag so the
script works regardless of which keys a pack already has. Placeholders are
kept identical to English (%1$d / %2$d / %1$s) so check_android_strings.py
placeholder validation passes.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
RES = ROOT / "android/app/src/main/res"

# locale-dir-name -> {name: value}. XML-escaped (apostrophes escaped, & as &amp;).
STRINGS = {
    "values-ar": {
        "fasting": "صيام",
        "fasting_idle": "لا يوجد صيام نشط",
        "fasting_goal_reached": "تم بلوغ الهدف",
        "fasting_goal_progress": "%1$s · الهدف %2$d ساعة",
        "fasting_duration_h_m": "%1$d س %2$d د",
        "fasting_duration_h": "%1$d س",
        "fasting_duration_m": "%1$d د",
        "fasting_start": "بدء الصيام",
        "fasting_stop": "إنهاء الصيام",
        "fasting_cancel": "إلغاء",
        "add_food_fasting_section": "صيام",
        "settings_fasting_title": "صيام",
        "settings_fasting_intro": "تتبّع نوافذ الصيام المتقطع بمؤقّت محلي: ابدأ أو أوقف أو ألغِ في أي وقت، مع مدة هدف اختيارية. يبقى المؤقّت على هذا الجهاز ولا تتم مزامنته أو تصديره أبدًا.",
        "settings_fasting_section_tracking": "التتبّع",
        "settings_fasting_tracking": "مؤقّت الصيام",
        "settings_fasting_goal": "مدة الهدف",
        "settings_fasting_goal_summary_none": "بلا هدف",
        "settings_fasting_goal_summary": "%1$d ساعة",
        "settings_fasting_goal_wheel_help": "يُرسَل إشعار واحد عند بلوغ الهدف. 0 = بلا هدف.",
        "settings_fasting_section_notification": "الإشعارات",
        "settings_fasting_notification": "بلوغ الهدف",
        "fasting_local_only_note": "يبقى مؤقّت الصيام على هذا الجهاز — لا تتم مزامنته أو تصديره أو تضمينه في الوجبات المشتركة. إشعار بلوغ الهدف هو الشيء الوحيد الذي ينشره Chompass عنه.",
        "shortcut_fasting_short": "صيام",
        "shortcut_fasting_long": "بدء أو إيقاف الصيام",
        "fasting_goal_unit_h": "س",
        "notif_channel_fasting": "صيام",
        "notif_channel_fasting_desc": "ملاحظة لمرة واحدة عند بلوغ هدف الصيام.",
        "notif_fasting_goal_title": "تم بلوغ هدف الصيام",
        "notif_fasting_goal_text": "اكتمل صيامك البالغ %1$d ساعة — يمكنك الإفطار الآن.",
    },
    "values-az": {
        "fasting": "Oruc",
        "fasting_idle": "Aktiv oruc yoxdur",
        "fasting_goal_reached": "Məqsədə çatdı",
        "fasting_goal_progress": "%1$s · məqsəd %2$d saat",
        "fasting_duration_h_m": "%1$d sa %2$d dəq",
        "fasting_duration_h": "%1$d sa",
        "fasting_duration_m": "%1$d dəq",
        "fasting_start": "Oruca başla",
        "fasting_stop": "Orucu bitir",
        "fasting_cancel": "Ləğv et",
        "add_food_fasting_section": "Oruc",
        "settings_fasting_title": "Oruc",
        "settings_fasting_intro": "Fasiləli oruc pəncərələrini yerli taymerlə izləyin: istənilən vaxt başlayın, dayandırın və ya ləğv edin, istəyə görə hədəf müddəti ilə. Taymer bu cihazda qalır və heç vaxt sinxronlaşdırılmır və ya ixrac edilmir.",
        "settings_fasting_section_tracking": "İzləmə",
        "settings_fasting_tracking": "Oruc taymeri",
        "settings_fasting_goal": "Hədəf müddəti",
        "settings_fasting_goal_summary_none": "Hədəf yoxdur",
        "settings_fasting_goal_summary": "%1$d saat",
        "settings_fasting_goal_wheel_help": "Hədəfə çatanda bir dəfəlik bildiriş gəlir. 0 = hədəf yoxdur.",
        "settings_fasting_section_notification": "Bildiriş",
        "settings_fasting_notification": "Hədəfə çatma",
        "fasting_local_only_note": "Oruc taymeri bu cihazda qalır — sinxronlaşdırılmır, ixrac edilmir və paylaşılan yeməklərə daxil edilmir. Chompass bu barədə yalnız hədəf bildirişini göndərir.",
        "shortcut_fasting_short": "Oruc",
        "shortcut_fasting_long": "Oruca başla və ya dayandır",
        "fasting_goal_unit_h": "sa",
        "notif_channel_fasting": "Oruc",
        "notif_channel_fasting_desc": "Oruc hədəfinə çatanda birdəfəlik qeyd.",
        "notif_fasting_goal_title": "Oruc hədəfinə çatdı",
        "notif_fasting_goal_text": "%1$d saatlıq orucunuz tamamlandı — indi yemək yeyə bilərsiniz.",
    },
    "values-de": {
        "fasting": "Fasten",
        "fasting_idle": "Kein aktives Fasten",
        "fasting_goal_reached": "Ziel erreicht",
        "fasting_goal_progress": "%1$s · Ziel %2$d h",
        "fasting_duration_h_m": "%1$d Std %2$d Min",
        "fasting_duration_h": "%1$d Std",
        "fasting_duration_m": "%1$d Min",
        "fasting_start": "Fasten starten",
        "fasting_stop": "Fasten beenden",
        "fasting_cancel": "Abbrechen",
        "add_food_fasting_section": "Fasten",
        "settings_fasting_title": "Fasten",
        "settings_fasting_intro": "Verfolge intermittierende Fastenfenster mit einem lokalen Timer: jederzeit starten, stoppen oder abbrechen, optional mit Ziellänge. Der Timer bleibt auf diesem Gerät und wird nie synchronisiert oder exportiert.",
        "settings_fasting_section_tracking": "Verfolgung",
        "settings_fasting_tracking": "Fasten-Timer",
        "settings_fasting_goal": "Ziellänge",
        "settings_fasting_goal_summary_none": "Kein Ziel",
        "settings_fasting_goal_summary": "%1$d h",
        "settings_fasting_goal_wheel_help": "Beim Erreichen des Ziels erscheint eine einmalige Benachrichtigung. 0 = kein Ziel.",
        "settings_fasting_section_notification": "Benachrichtigung",
        "settings_fasting_notification": "Ziel erreicht",
        "fasting_local_only_note": "Der Fasten-Timer bleibt auf diesem Gerät — er wird nie synchronisiert, exportiert oder in geteilte Mahlzeiten aufgenommen. Die Ziel-Benachrichtigung ist das Einzige, was Chompass darüber sendet.",
        "shortcut_fasting_short": "Fasten",
        "shortcut_fasting_long": "Fasten starten oder stoppen",
        "fasting_goal_unit_h": "h",
        "notif_channel_fasting": "Fasten",
        "notif_channel_fasting_desc": "Einmalige Mitteilung, wenn ein Fastenziel erreicht ist.",
        "notif_fasting_goal_title": "Fastenziel erreicht",
        "notif_fasting_goal_text": "Dein %1$d-stündiges Fasten ist abgeschlossen — du kannst jetzt deine Fastenpause beenden.",
    },
    "values-es": {
        "fasting": "Ayuno",
        "fasting_idle": "Sin ayuno activo",
        "fasting_goal_reached": "Objetivo alcanzado",
        "fasting_goal_progress": "%1$s · objetivo %2$d h",
        "fasting_duration_h_m": "%1$d h %2$d min",
        "fasting_duration_h": "%1$d h",
        "fasting_duration_m": "%1$d min",
        "fasting_start": "Iniciar ayuno",
        "fasting_stop": "Terminar ayuno",
        "fasting_cancel": "Cancelar",
        "add_food_fasting_section": "Ayuno",
        "settings_fasting_title": "Ayuno",
        "settings_fasting_intro": "Sigue ventanas de ayuno intermitente con un temporizador local: inicia, detén o cancela cuando quieras, con una duración objetivo opcional. El temporizador se queda en este dispositivo y nunca se sincroniza ni se exporta.",
        "settings_fasting_section_tracking": "Seguimiento",
        "settings_fasting_tracking": "Temporizador de ayuno",
        "settings_fasting_goal": "Duración objetivo",
        "settings_fasting_goal_summary_none": "Sin objetivo",
        "settings_fasting_goal_summary": "%1$d h",
        "settings_fasting_goal_wheel_help": "Se envía una notificación única al alcanzar el objetivo. 0 = sin objetivo.",
        "settings_fasting_section_notification": "Notificación",
        "settings_fasting_notification": "Objetivo alcanzado",
        "fasting_local_only_note": "El temporizador de ayuno se queda en este dispositivo: nunca se sincroniza, exporta ni incluye en comidas compartidas. La notificación de objetivo alcanzado es lo único que Chompass publica al respecto.",
        "shortcut_fasting_short": "Ayuno",
        "shortcut_fasting_long": "Iniciar o detener el ayuno",
        "fasting_goal_unit_h": "h",
        "notif_channel_fasting": "Ayuno",
        "notif_channel_fasting_desc": "Aviso único cuando se alcanza un objetivo de ayuno.",
        "notif_fasting_goal_title": "Objetivo de ayuno alcanzado",
        "notif_fasting_goal_text": "Tu ayuno de %1$d h ha terminado: ya puedes comer.",
    },
    "values-fr": {
        "fasting": "Jeûne",
        "fasting_idle": "Aucun jeûne en cours",
        "fasting_goal_reached": "Objectif atteint",
        "fasting_goal_progress": "%1$s · objectif %2$d h",
        "fasting_duration_h_m": "%1$d h %2$d min",
        "fasting_duration_h": "%1$d h",
        "fasting_duration_m": "%1$d min",
        "fasting_start": "Démarrer le jeûne",
        "fasting_stop": "Arrêter le jeûne",
        "fasting_cancel": "Annuler",
        "add_food_fasting_section": "Jeûne",
        "settings_fasting_title": "Jeûne",
        "settings_fasting_intro": "Suivez vos fenêtres de jeûne intermittent avec un minuteur local : démarrez, arrêtez ou annulez à tout moment, avec une durée objectif facultative. Le minuteur reste sur cet appareil et n'est jamais synchronisé ni exporté.",
        "settings_fasting_section_tracking": "Suivi",
        "settings_fasting_tracking": "Minuteur de jeûne",
        "settings_fasting_goal": "Durée objectif",
        "settings_fasting_goal_summary_none": "Aucun objectif",
        "settings_fasting_goal_summary": "%1$d h",
        "settings_fasting_goal_wheel_help": "Une notification unique est envoyée lorsque l'objectif est atteint. 0 = aucun objectif.",
        "settings_fasting_section_notification": "Notification",
        "settings_fasting_notification": "Objectif atteint",
        "fasting_local_only_note": "Le minuteur de jeûne reste sur cet appareil : il n'est jamais synchronisé, exporté ni inclus dans les repas partagés. La notification d'objectif atteint est la seule chose que Chompass publie à son sujet.",
        "shortcut_fasting_short": "Jeûne",
        "shortcut_fasting_long": "Démarrer ou arrêter le jeûne",
        "fasting_goal_unit_h": "h",
        "notif_channel_fasting": "Jeûne",
        "notif_channel_fasting_desc": "Avis unique lorsqu'un objectif de jeûne est atteint.",
        "notif_fasting_goal_title": "Objectif de jeûne atteint",
        "notif_fasting_goal_text": "Votre jeûne de %1$d h est terminé : vous pouvez rompre votre jeûne maintenant.",
    },
    "values-hi": {
        "fasting": "उपवास",
        "fasting_idle": "कोई सक्रिय उपवास नहीं",
        "fasting_goal_reached": "लक्ष्य प्राप्त हुआ",
        "fasting_goal_progress": "%1$s · लक्ष्य %2$d घंटे",
        "fasting_duration_h_m": "%1$d घं %2$d मि",
        "fasting_duration_h": "%1$d घं",
        "fasting_duration_m": "%1$d मि",
        "fasting_start": "उपवास शुरू करें",
        "fasting_stop": "उपवास समाप्त करें",
        "fasting_cancel": "रद्द करें",
        "add_food_fasting_section": "उपवास",
        "settings_fasting_title": "उपवास",
        "settings_fasting_intro": "स्थानीय टाइमर से आंतरायिक उपवास विंडो ट्रैक करें: कभी भी शुरू करें, रोकें या रद्द करें, वैकल्पिक लक्ष्य अवधि के साथ। टाइमर इसी डिवाइस पर रहता है और कभी सिंक या निर्यात नहीं होता।",
        "settings_fasting_section_tracking": "ट्रैकिंग",
        "settings_fasting_tracking": "उपवास टाइमर",
        "settings_fasting_goal": "लक्ष्य अवधि",
        "settings_fasting_goal_summary_none": "कोई लक्ष्य नहीं",
        "settings_fasting_goal_summary": "%1$d घंटे",
        "settings_fasting_goal_wheel_help": "लक्ष्य पूरा होने पर एक बार सूचना मिलती है। 0 = कोई लक्ष्य नहीं।",
        "settings_fasting_section_notification": "सूचना",
        "settings_fasting_notification": "लक्ष्य प्राप्त हुआ",
        "fasting_local_only_note": "उपवास टाइमर इसी डिवाइस पर रहता है — इसे कभी सिंक, निर्यात या साझा भोजन में शामिल नहीं किया जाता। लक्ष्य-प्राप्ति सूचना ही Chompass इसके बारे में भेजता है।",
        "shortcut_fasting_short": "उपवास",
        "shortcut_fasting_long": "उपवास शुरू या रोकें",
        "fasting_goal_unit_h": "घं",
        "notif_channel_fasting": "उपवास",
        "notif_channel_fasting_desc": "उपवास लक्ष्य पूरा होने पर एक बार का नोट।",
        "notif_fasting_goal_title": "उपवास लक्ष्य प्राप्त हुआ",
        "notif_fasting_goal_text": "आपका %1$d घंटे का उपवास पूरा हुआ — अब आप उपवास तोड़ सकते हैं।",
    },
    "values-it": {
        "fasting": "Digiuno",
        "fasting_idle": "Nessun digiuno attivo",
        "fasting_goal_reached": "Obiettivo raggiunto",
        "fasting_goal_progress": "%1$s · obiettivo %2$d h",
        "fasting_duration_h_m": "%1$d h %2$d min",
        "fasting_duration_h": "%1$d h",
        "fasting_duration_m": "%1$d min",
        "fasting_start": "Inizia digiuno",
        "fasting_stop": "Termina digiuno",
        "fasting_cancel": "Annulla",
        "add_food_fasting_section": "Digiuno",
        "settings_fasting_title": "Digiuno",
        "settings_fasting_intro": "Tieni traccia dei periodi di digiuno intermittente con un timer locale: inizia, ferma o annulla quando vuoi, con una durata obiettivo opzionale. Il timer resta su questo dispositivo e non viene mai sincronizzato né esportato.",
        "settings_fasting_section_tracking": "Monitoraggio",
        "settings_fasting_tracking": "Timer digiuno",
        "settings_fasting_goal": "Durata obiettivo",
        "settings_fasting_goal_summary_none": "Nessun obiettivo",
        "settings_fasting_goal_summary": "%1$d h",
        "settings_fasting_goal_wheel_help": "Una notifica una tantum viene inviata al raggiungimento dell'obiettivo. 0 = nessun obiettivo.",
        "settings_fasting_section_notification": "Notifica",
        "settings_fasting_notification": "Obiettivo raggiunto",
        "fasting_local_only_note": "Il timer del digiuno resta su questo dispositivo: non viene mai sincronizzato, esportato o incluso nei pasti condivisi. La notifica di obiettivo raggiunto è l'unica cosa che Chompass pubblica al riguardo.",
        "shortcut_fasting_short": "Digiuno",
        "shortcut_fasting_long": "Inizia o ferma il digiuno",
        "fasting_goal_unit_h": "h",
        "notif_channel_fasting": "Digiuno",
        "notif_channel_fasting_desc": "Avviso una tantum quando un obiettivo di digiuno viene raggiunto.",
        "notif_fasting_goal_title": "Obiettivo digiuno raggiunto",
        "notif_fasting_goal_text": "Il tuo digiuno di %1$d h è completo: ora puoi mangiare.",
    },
    "values-ja": {
        "fasting": "ファスティング",
        "fasting_idle": "進行中のファスティングはありません",
        "fasting_goal_reached": "目標達成",
        "fasting_goal_progress": "%1$s · 目標 %2$d 時間",
        "fasting_duration_h_m": "%1$d 時間 %2$d 分",
        "fasting_duration_h": "%1$d 時間",
        "fasting_duration_m": "%1$d 分",
        "fasting_start": "ファスティング開始",
        "fasting_stop": "ファスティング終了",
        "fasting_cancel": "キャンセル",
        "add_food_fasting_section": "ファスティング",
        "settings_fasting_title": "ファスティング",
        "settings_fasting_intro": "ローカルのタイマーで間欠的ファスティングの時間帯を記録できます。いつでも開始・停止・キャンセルでき、目標時間も任意で設定可能。タイマーはこの端末にのみ保存され、同期や書き出しは一切行われません。",
        "settings_fasting_section_tracking": "記録",
        "settings_fasting_tracking": "ファスティングタイマー",
        "settings_fasting_goal": "目標時間",
        "settings_fasting_goal_summary_none": "目標なし",
        "settings_fasting_goal_summary": "%1$d 時間",
        "settings_fasting_goal_wheel_help": "目標に到達すると通知が1回送信されます。0 = 目標なし。",
        "settings_fasting_section_notification": "通知",
        "settings_fasting_notification": "目標達成",
        "fasting_local_only_note": "ファスティングタイマーはこの端末にのみ保存されます。同期・書き出し・共有メニューへの組み込みは一切行われません。Chompassが送信するのは目標達成通知のみです。",
        "shortcut_fasting_short": "ファスティング",
        "shortcut_fasting_long": "ファスティングを開始または終了",
        "fasting_goal_unit_h": "時間",
        "notif_channel_fasting": "ファスティング",
        "notif_channel_fasting_desc": "ファスティング目標達成時の1回限りの通知。",
        "notif_fasting_goal_title": "ファスティング目標達成",
        "notif_fasting_goal_text": "%1$d 時間のファスティングが完了しました。そろそろ食事を始められます。",
    },
    "values-ko": {
        "fasting": "단식",
        "fasting_idle": "진행 중인 단식 없음",
        "fasting_goal_reached": "목표 달성",
        "fasting_goal_progress": "%1$s · 목표 %2$d시간",
        "fasting_duration_h_m": "%1$d시간 %2$d분",
        "fasting_duration_h": "%1$d시간",
        "fasting_duration_m": "%1$d분",
        "fasting_start": "단식 시작",
        "fasting_stop": "단식 종료",
        "fasting_cancel": "취소",
        "add_food_fasting_section": "단식",
        "settings_fasting_title": "단식",
        "settings_fasting_intro": "로컬 타이머로 간헐적 단식 시간을 기록하세요. 언제든 시작, 중지 또는 취소할 수 있고 목표 시간도 선택 사항입니다. 타이머는 이 기기에만 남으며 동기화되거나 내보내지지 않습니다.",
        "settings_fasting_section_tracking": "기록",
        "settings_fasting_tracking": "단식 타이머",
        "settings_fasting_goal": "목표 시간",
        "settings_fasting_goal_summary_none": "목표 없음",
        "settings_fasting_goal_summary": "%1$d시간",
        "settings_fasting_goal_wheel_help": "목표에 도달하면 알림이 한 번 발송됩니다. 0 = 목표 없음.",
        "settings_fasting_section_notification": "알림",
        "settings_fasting_notification": "목표 달성",
        "fasting_local_only_note": "단식 타이머는 이 기기에만 남습니다. 동기화, 내보내기 또는 공유 식사에 포함되지 않으며, Chompass가 이에 대해 게시하는 것은 목표 달성 알림뿐입니다.",
        "shortcut_fasting_short": "단식",
        "shortcut_fasting_long": "단식 시작 또는 종료",
        "fasting_goal_unit_h": "시간",
        "notif_channel_fasting": "단식",
        "notif_channel_fasting_desc": "단식 목표 달성 시 1회 알림.",
        "notif_fasting_goal_title": "단식 목표 달성",
        "notif_fasting_goal_text": "%1$d시간 단식이 완료되었습니다. 이제 식사를 시작할 수 있습니다.",
    },
    "values-nl": {
        "fasting": "Vasten",
        "fasting_idle": "Geen actief vasten",
        "fasting_goal_reached": "Doel bereikt",
        "fasting_goal_progress": "%1$s · doel %2$d u",
        "fasting_duration_h_m": "%1$d u %2$d min",
        "fasting_duration_h": "%1$d u",
        "fasting_duration_m": "%1$d min",
        "fasting_start": "Vasten starten",
        "fasting_stop": "Vasten stoppen",
        "fasting_cancel": "Annuleren",
        "add_food_fasting_section": "Vasten",
        "settings_fasting_title": "Vasten",
        "settings_fasting_intro": "Volg periodes van intermittent fasting met een lokale timer: start, stop of annuleer wanneer je wilt, met een optionele doellengte. De timer blijft op dit apparaat en wordt nooit gesynchroniseerd of geëxporteerd.",
        "settings_fasting_section_tracking": "Bijhouden",
        "settings_fasting_tracking": "Vastentimer",
        "settings_fasting_goal": "Doellengte",
        "settings_fasting_goal_summary_none": "Geen doel",
        "settings_fasting_goal_summary": "%1$d u",
        "settings_fasting_goal_wheel_help": "Wanneer je het doel bereikt, verschijnt een eenmalige melding. 0 = geen doel.",
        "settings_fasting_section_notification": "Melding",
        "settings_fasting_notification": "Doel bereikt",
        "fasting_local_only_note": "De vastentimer blijft op dit apparaat: hij wordt nooit gesynchroniseerd, geëxporteerd of toegevoegd aan gedeelde maaltijden. De doel-berichtmelding is het enige wat Chompass hierover plaatst.",
        "shortcut_fasting_short": "Vasten",
        "shortcut_fasting_long": "Vasten starten of stoppen",
        "fasting_goal_unit_h": "u",
        "notif_channel_fasting": "Vasten",
        "notif_channel_fasting_desc": "Eenmalig bericht wanneer een vastendoel is bereikt.",
        "notif_fasting_goal_title": "Vastendoel bereikt",
        "notif_fasting_goal_text": "Je vasten van %1$d u is voltooid — je kunt nu eten.",
    },
    "values-pl": {
        "fasting": "Post",
        "fasting_idle": "Brak aktywnego postu",
        "fasting_goal_reached": "Osiągnięto cel",
        "fasting_goal_progress": "%1$s · cel %2$d h",
        "fasting_duration_h_m": "%1$d h %2$d min",
        "fasting_duration_h": "%1$d h",
        "fasting_duration_m": "%1$d min",
        "fasting_start": "Rozpocznij post",
        "fasting_stop": "Zakończ post",
        "fasting_cancel": "Anuluj",
        "add_food_fasting_section": "Post",
        "settings_fasting_title": "Post",
        "settings_fasting_intro": "Śledź okna postu przerywanego za pomocą lokalnego timera: zacznij, zatrzymaj lub anuluj w dowolnym momencie, z opcjonalną długością celu. Timer pozostaje na tym urządzeniu i nigdy nie jest synchronizowany ani eksportowany.",
        "settings_fasting_section_tracking": "Śledzenie",
        "settings_fasting_tracking": "Timer postu",
        "settings_fasting_goal": "Długość celu",
        "settings_fasting_goal_summary_none": "Brak celu",
        "settings_fasting_goal_summary": "%1$d h",
        "settings_fasting_goal_wheel_help": "Po osiągnięciu celu wysyłane jest jednorazowe powiadomienie. 0 = brak celu.",
        "settings_fasting_section_notification": "Powiadomienie",
        "settings_fasting_notification": "Osiągnięto cel",
        "fasting_local_only_note": "Timer postu pozostaje na tym urządzeniu — nigdy nie jest synchronizowany, eksportowany ani dołączany do udostępnianych posiłków. Jedyną rzeczą, którą Chompass o nim publikuje, jest powiadomienie o osiągnięciu celu.",
        "shortcut_fasting_short": "Post",
        "shortcut_fasting_long": "Rozpocznij lub zatrzymaj post",
        "fasting_goal_unit_h": "h",
        "notif_channel_fasting": "Post",
        "notif_channel_fasting_desc": "Jednorazowa wiadomość po osiągnięciu celu postu.",
        "notif_fasting_goal_title": "Osiągnięto cel postu",
        "notif_fasting_goal_text": "Twój %1$d-godzinny post zakończony — możesz teraz przerwać post.",
    },
    "values-pt-rBR": {
        "fasting": "Jejum",
        "fasting_idle": "Sem jejum ativo",
        "fasting_goal_reached": "Meta atingida",
        "fasting_goal_progress": "%1$s · meta %2$d h",
        "fasting_duration_h_m": "%1$d h %2$d min",
        "fasting_duration_h": "%1$d h",
        "fasting_duration_m": "%1$d min",
        "fasting_start": "Iniciar jejum",
        "fasting_stop": "Encerrar jejum",
        "fasting_cancel": "Cancelar",
        "add_food_fasting_section": "Jejum",
        "settings_fasting_title": "Jejum",
        "settings_fasting_intro": "Acompanhe janelas de jejum intermitente com um timer local: inicie, pare ou cancele quando quiser, com uma duração de meta opcional. O timer fica neste dispositivo e nunca é sincronizado nem exportado.",
        "settings_fasting_section_tracking": "Acompanhamento",
        "settings_fasting_tracking": "Timer de jejum",
        "settings_fasting_goal": "Duração da meta",
        "settings_fasting_goal_summary_none": "Sem meta",
        "settings_fasting_goal_summary": "%1$d h",
        "settings_fasting_goal_wheel_help": "Uma notificação única é enviada ao atingir a meta. 0 = sem meta.",
        "settings_fasting_section_notification": "Notificação",
        "settings_fasting_notification": "Meta atingida",
        "fasting_local_only_note": "O timer de jejum fica neste dispositivo: nunca é sincronizado, exportado nem incluído em refeições compartilhadas. A notificação de meta atingida é a única coisa que o Chompass publica sobre ele.",
        "shortcut_fasting_short": "Jejum",
        "shortcut_fasting_long": "Iniciar ou encerrar o jejum",
        "fasting_goal_unit_h": "h",
        "notif_channel_fasting": "Jejum",
        "notif_channel_fasting_desc": "Aviso único quando uma meta de jejum é atingida.",
        "notif_fasting_goal_title": "Meta de jejum atingida",
        "notif_fasting_goal_text": "Seu jejum de %1$d h terminou — você já pode comer.",
    },
    "values-ro": {
        "fasting": "Post",
        "fasting_idle": "Niciun post activ",
        "fasting_goal_reached": "Obiectiv atins",
        "fasting_goal_progress": "%1$s · obiectiv %2$d h",
        "fasting_duration_h_m": "%1$d h %2$d min",
        "fasting_duration_h": "%1$d h",
        "fasting_duration_m": "%1$d min",
        "fasting_start": "Începe postul",
        "fasting_stop": "Oprește postul",
        "fasting_cancel": "Anulează",
        "add_food_fasting_section": "Post",
        "settings_fasting_title": "Post",
        "settings_fasting_intro": "Urmărește ferestrele de post intermitent cu un cronometru local: începe, oprește sau anulează oricând, cu o durată-țintă opțională. Cronometrul rămâne pe acest dispozitiv și nu este niciodată sincronizat sau exportat.",
        "settings_fasting_section_tracking": "Urmărire",
        "settings_fasting_tracking": "Cronometru post",
        "settings_fasting_goal": "Durata țintei",
        "settings_fasting_goal_summary_none": "Fără țintă",
        "settings_fasting_goal_summary": "%1$d h",
        "settings_fasting_goal_wheel_help": "O notificare unică este trimisă când atingi ținta. 0 = fără țintă.",
        "settings_fasting_section_notification": "Notificare",
        "settings_fasting_notification": "Obiectiv atins",
        "fasting_local_only_note": "Cronometrul de post rămâne pe acest dispozitiv — nu este niciodată sincronizat, exportat sau inclus în mesele partajate. Notificarea de atingere a țintei este singurul lucru pe care Chompass îl publică despre el.",
        "shortcut_fasting_short": "Post",
        "shortcut_fasting_long": "Începe sau oprește postul",
        "fasting_goal_unit_h": "h",
        "notif_channel_fasting": "Post",
        "notif_channel_fasting_desc": "Notă unică atunci când o țintă de post este atinsă.",
        "notif_fasting_goal_title": "Ținta de post atinsă",
        "notif_fasting_goal_text": "Postul tău de %1$d h s-a încheiat — poți mânca acum.",
    },
    "values-ru": {
        "fasting": "Пост",
        "fasting_idle": "Нет активного поста",
        "fasting_goal_reached": "Цель достигнута",
        "fasting_goal_progress": "%1$s · цель %2$d ч",
        "fasting_duration_h_m": "%1$d ч %2$d мин",
        "fasting_duration_h": "%1$d ч",
        "fasting_duration_m": "%1$d мин",
        "fasting_start": "Начать пост",
        "fasting_stop": "Завершить пост",
        "fasting_cancel": "Отмена",
        "add_food_fasting_section": "Пост",
        "settings_fasting_title": "Пост",
        "settings_fasting_intro": "Отслеживайте окна интервального голодания с помощью локального таймера: начинайте, останавливайте или отменяйте в любой момент, с опциональной целевой длительностью. Таймер остаётся на этом устройстве и никогда не синхронизируется и не экспортируется.",
        "settings_fasting_section_tracking": "Отслеживание",
        "settings_fasting_tracking": "Таймер поста",
        "settings_fasting_goal": "Целевая длительность",
        "settings_fasting_goal_summary_none": "Без цели",
        "settings_fasting_goal_summary": "%1$d ч",
        "settings_fasting_goal_wheel_help": "При достижении цели отправляется одно уведомление. 0 = без цели.",
        "settings_fasting_section_notification": "Уведомление",
        "settings_fasting_notification": "Цель достигнута",
        "fasting_local_only_note": "Таймер поста остаётся на этом устройстве — он никогда не синхронизируется, не экспортируется и не включается в общие приёмы пищи. Уведомление о достижении цели — единственное, что Chompass публикует о нём.",
        "shortcut_fasting_short": "Пост",
        "shortcut_fasting_long": "Начать или остановить пост",
        "fasting_goal_unit_h": "ч",
        "notif_channel_fasting": "Пост",
        "notif_channel_fasting_desc": "Одноразовое уведомление о достижении цели поста.",
        "notif_fasting_goal_title": "Цель поста достигнута",
        "notif_fasting_goal_text": "Ваш %1$d-часовой пост завершён — теперь можно прервать пост.",
    },
    "values-tr": {
        "fasting": "Oruç",
        "fasting_idle": "Aktif oruç yok",
        "fasting_goal_reached": "Hedefe ulaşıldı",
        "fasting_goal_progress": "%1$s · hedef %2$d saat",
        "fasting_duration_h_m": "%1$d sa %2$d dk",
        "fasting_duration_h": "%1$d sa",
        "fasting_duration_m": "%1$d dk",
        "fasting_start": "Orucu başlat",
        "fasting_stop": "Orucu bitir",
        "fasting_cancel": "İptal",
        "add_food_fasting_section": "Oruç",
        "settings_fasting_title": "Oruç",
        "settings_fasting_intro": "Yerel bir zamanlayıcıyla aralıklı oruç pencerelerini takip edin: isteğe bağlı hedef süresiyle istediğiniz zaman başlatın, durdurun veya iptal edin. Zamanlayıcı bu cihazda kalır ve asla senkronize edilmez veya dışa aktarılmaz.",
        "settings_fasting_section_tracking": "Takip",
        "settings_fasting_tracking": "Oruç zamanlayıcısı",
        "settings_fasting_goal": "Hedef süresi",
        "settings_fasting_goal_summary_none": "Hedef yok",
        "settings_fasting_goal_summary": "%1$d saat",
        "settings_fasting_goal_wheel_help": "Hedefe ulaşıldığında bir kez bildirim gönderilir. 0 = hedef yok.",
        "settings_fasting_section_notification": "Bildirim",
        "settings_fasting_notification": "Hedefe ulaşıldı",
        "fasting_local_only_note": "Oruç zamanlayıcısı bu cihazda kalır — asla senkronize edilmez, dışa aktarılmaz veya paylaşılan öğünlere dahil edilmez. Chompass'ın bu konuda yayınladığı tek şey hedef bildirimidir.",
        "shortcut_fasting_short": "Oruç",
        "shortcut_fasting_long": "Orucu başlat veya durdur",
        "fasting_goal_unit_h": "sa",
        "notif_channel_fasting": "Oruç",
        "notif_channel_fasting_desc": "Oruç hedefine ulaşıldığında tek seferlik bildirim.",
        "notif_fasting_goal_title": "Oruç hedefine ulaşıldı",
        "notif_fasting_goal_text": "%1$d saatlik orucunuz tamamlandı — artık yemek yiyebilirsiniz.",
    },
    "values-uk": {
        "fasting": "Пост",
        "fasting_idle": "Немає активного посту",
        "fasting_goal_reached": "Мета досягнута",
        "fasting_goal_progress": "%1$s · мета %2$d год",
        "fasting_duration_h_m": "%1$d год %2$d хв",
        "fasting_duration_h": "%1$d год",
        "fasting_duration_m": "%1$d хв",
        "fasting_start": "Почати пост",
        "fasting_stop": "Завершити пост",
        "fasting_cancel": "Скасувати",
        "add_food_fasting_section": "Пост",
        "settings_fasting_title": "Пост",
        "settings_fasting_intro": "Відстежуйте вікна інтервального голодування за допомогою локального таймера: починайте, зупиняйте або скасовуйте будь-коли, з необов\'язковою цільовою тривалістю. Таймер залишається на цьому пристрої й ніколи не синхронізується та не експортується.",
        "settings_fasting_section_tracking": "Відстеження",
        "settings_fasting_tracking": "Таймер посту",
        "settings_fasting_goal": "Цільова тривалість",
        "settings_fasting_goal_summary_none": "Без цілі",
        "settings_fasting_goal_summary": "%1$d год",
        "settings_fasting_goal_wheel_help": "Після досягнення цілі надсилається одне сповіщення. 0 = без цілі.",
        "settings_fasting_section_notification": "Сповіщення",
        "settings_fasting_notification": "Мета досягнута",
        "fasting_local_only_note": "Таймер посту залишається на цьому пристрої — він ніколи не синхронізується, не експортується та не додається до спільних прийомів їжі. Єдине, що Chompass публікує про нього, — сповіщення про досягнення цілі.",
        "shortcut_fasting_short": "Пост",
        "shortcut_fasting_long": "Почати або зупинити пост",
        "fasting_goal_unit_h": "год",
        "notif_channel_fasting": "Пост",
        "notif_channel_fasting_desc": "Одноразове сповіщення про досягнення цілі посту.",
        "notif_fasting_goal_title": "Ціль посту досягнута",
        "notif_fasting_goal_text": "Ваш %1$d-годинний пост завершено — тепер можна перервати пост.",
    },
    "values-zh-rCN": {
        "fasting": "间歇性禁食",
        "fasting_idle": "无进行中的禁食",
        "fasting_goal_reached": "已达目标",
        "fasting_goal_progress": "%1$s · 目标 %2$d 小时",
        "fasting_duration_h_m": "%1$d 小时 %2$d 分",
        "fasting_duration_h": "%1$d 小时",
        "fasting_duration_m": "%1$d 分",
        "fasting_start": "开始禁食",
        "fasting_stop": "结束禁食",
        "fasting_cancel": "取消",
        "add_food_fasting_section": "间歇性禁食",
        "settings_fasting_title": "间歇性禁食",
        "settings_fasting_intro": "使用本地计时器跟踪间歇性禁食时段：可随时开始、停止或取消，并可设置可选的目标时长。计时器仅保存在此设备上，绝不会同步或导出。",
        "settings_fasting_section_tracking": "跟踪",
        "settings_fasting_tracking": "禁食计时器",
        "settings_fasting_goal": "目标时长",
        "settings_fasting_goal_summary_none": "无目标",
        "settings_fasting_goal_summary": "%1$d 小时",
        "settings_fasting_goal_wheel_help": "达到目标时会发送一次通知。0 = 无目标。",
        "settings_fasting_section_notification": "通知",
        "settings_fasting_notification": "已达目标",
        "fasting_local_only_note": "禁食计时器仅保存在此设备上，绝不会同步、导出或包含在共享餐食中。Chompass 只会针对它发布达到目标的提醒。",
        "shortcut_fasting_short": "禁食",
        "shortcut_fasting_long": "开始或结束禁食",
        "fasting_goal_unit_h": "小时",
        "notif_channel_fasting": "间歇性禁食",
        "notif_channel_fasting_desc": "达到禁食目标时的一次性提醒。",
        "notif_fasting_goal_title": "禁食目标达成",
        "notif_fasting_goal_text": "您的 %1$d 小时禁食已完成，现在可以进食了。",
    },
}


def xml_escape(value: str) -> str:
    return value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def main() -> int:
    for folder, keys in STRINGS.items():
        path = RES / folder / "strings.xml"
        text = path.read_text(encoding="utf-8")
        if "name=\"fasting\"" in text:
            print(f"skip {folder}: fasting keys already present")
            continue
        block = "\n".join(
            f'    <string name="{name}">{xml_escape(value)}</string>'
            for name, value in keys.items()
        )
        if "</resources>" not in text:
            print(f"ERROR {folder}: no </resources> anchor")
            return 1
        text = text.replace("</resources>", block + "\n</resources>", 1)
        path.write_text(text, encoding="utf-8")
        print(f"ok {folder}: inserted {len(keys)} strings")
    return 0


if __name__ == "__main__":
    sys.exit(main())
